import { MAX_CONTROL_TEXT_BYTES } from "./protocol.js";
export interface ChatSurfaceAdapter { isSupported(): Promise<boolean>; sendControlText(text: string): Promise<void>; observeAssistantControls(onControl: (text: string) => void): () => void; conversationIdentity(): Promise<string | null>; }
export interface ChatGptSurfaceDependencies { document: Document; location: Location; createObserver?: (callback: MutationCallback) => { observe(target: Node, options?: MutationObserverInit): void; disconnect(): void }; }
const COMPOSER_SELECTORS = ["#prompt-textarea[contenteditable='true']", "textarea#prompt-textarea", "textarea[data-testid='prompt-textarea']"] as const;
const SEND_SELECTORS = ["button[data-testid='send-button']", "button[aria-label='Send prompt']", "button[aria-label='Send message']"] as const;
const MESSAGE_SELECTOR = "[data-message-author-role]"; const MAX_MESSAGE_SCAN = 200;
function uniqueMatches<T extends Element>(document: Document, selectors: readonly string[]): T[] { const matches = new Set<T>(); for (const selector of selectors) for (const element of document.querySelectorAll<T>(selector)) matches.add(element); return [...matches]; }
function isSendButton(element: Element): element is HTMLButtonElement { return element.tagName.toLowerCase() === "button" && typeof (element as HTMLButtonElement).click === "function"; }
function isTextArea(element: Element): element is HTMLTextAreaElement { return element.tagName.toLowerCase() === "textarea" && "value" in element; }
function isEditable(element: Element): element is HTMLElement { return "isContentEditable" in element && (element as HTMLElement).isContentEditable; }
function controlTextFromAssistant(element: Element): string | null { if (element.getAttribute("data-message-author-role") !== "assistant") return null; const text = element.textContent ?? ""; if (new TextEncoder().encode(text).byteLength > MAX_CONTROL_TEXT_BYTES) return null; const firstLine = text.split(/\r?\n|\r/, 1)[0] ?? ""; return firstLine === "[CHAT2CODEX]" ? text : null; }
function dispatchInputEvents(element: HTMLElement): void { element.dispatchEvent(new Event("input", { bubbles: true, composed: true })); element.dispatchEvent(new Event("change", { bubbles: true })); }
export class ChatGptSurfaceAdapter implements ChatSurfaceAdapter {
  constructor(private readonly dependencies: ChatGptSurfaceDependencies) {}
  async isSupported(): Promise<boolean> { return this.resolveSurface() !== null; }
  async sendControlText(text: string): Promise<void> { const byteLength = new TextEncoder().encode(text).byteLength; if (byteLength > MAX_CONTROL_TEXT_BYTES) throw new Error("RELAY_CONTROL_TEXT_TOO_LARGE"); if (byteLength === 0) throw new Error("RELAY_CONTROL_TEXT_INVALID"); const surface = this.resolveSurface(); if (!surface) throw new Error("RELAY_UI_UNSUPPORTED"); const { composer, send } = surface; if (isTextArea(composer)) { const setter = typeof HTMLTextAreaElement !== "undefined" ? Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, "value")?.set : undefined; if (setter) setter.call(composer, text); else composer.value = text; } else if (isEditable(composer)) composer.textContent = text; else throw new Error("RELAY_UI_UNSUPPORTED"); dispatchInputEvents(composer as HTMLElement); await Promise.resolve(); send.click(); }
  observeAssistantControls(onControl: (text: string) => void): () => void { const lastTextByNode = new WeakMap<Element, string>(); const scan = () => { const messages = [...this.dependencies.document.querySelectorAll(MESSAGE_SELECTOR)].slice(-MAX_MESSAGE_SCAN); for (const message of messages) { const control = controlTextFromAssistant(message); if (control === null || lastTextByNode.get(message) === control) continue; lastTextByNode.set(message, control); onControl(control); } }; scan(); const observer = this.dependencies.createObserver ? this.dependencies.createObserver(() => scan()) : new MutationObserver(() => scan()); observer.observe(this.dependencies.document.documentElement, { childList: true, subtree: true, characterData: true }); return () => observer.disconnect(); }
  async conversationIdentity(): Promise<string | null> { const match = this.dependencies.location.pathname.match(/^\/c\/([^/?#]+)(?:\/|$)/); return match?.[1] ?? null; }
  private resolveSurface(): { composer: Element; send: HTMLButtonElement } | null { const composers = uniqueMatches(this.dependencies.document, COMPOSER_SELECTORS); const sends = uniqueMatches(this.dependencies.document, SEND_SELECTORS).filter(isSendButton); if (composers.length !== 1 || sends.length !== 1) return null; const composer = composers[0]!; return isTextArea(composer) || isEditable(composer) ? { composer, send: sends[0]! } : null; }
}
