import { ChatGptSurfaceAdapter } from "./chat-surface.js";
import { MAX_CONTROL_TEXT_BYTES, WORKSPACE_ID_PATTERN, type RelayClientFrame } from "./protocol.js";
const EXTENSION_RELAY_STATE_KEY = "chat2codex_relay_state";
interface ContentRelayState { workspace_id: string; conversation_id: string | null; }
interface DeliverControlMessage { type: "deliver_control"; workspace_id: string; envelope_id: string; text: string; }
interface ChromeLike { storage: { local: { get(key: string): Promise<Record<string, unknown>> } }; runtime: { sendMessage(message: unknown): Promise<unknown>; onMessage: { addListener(listener: (message: unknown) => void): void } }; }
declare const chrome: ChromeLike | undefined;
function isDeliverControl(value: unknown): value is DeliverControlMessage { if (value === null || typeof value !== "object") return false; const record = value as Record<string, unknown>; return record.type === "deliver_control" && typeof record.workspace_id === "string" && WORKSPACE_ID_PATTERN.test(record.workspace_id) && typeof record.envelope_id === "string" && record.envelope_id.length > 0 && record.envelope_id.length <= 256 && typeof record.text === "string" && new TextEncoder().encode(record.text).byteLength <= MAX_CONTROL_TEXT_BYTES; }
async function fingerprint(text: string): Promise<string> { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text)); return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
export function initializeContentScript(api: ChromeLike, documentRef: Document, locationRef: Location): () => void {
  const surface = new ChatGptSurfaceAdapter({ document: documentRef, location: locationRef });
  const loadState = async (): Promise<ContentRelayState | null> => { const record = await api.storage.local.get(EXTENSION_RELAY_STATE_KEY); const value = record[EXTENSION_RELAY_STATE_KEY]; if (value === null || typeof value !== "object") return null; const state = value as Partial<ContentRelayState>; if (typeof state.workspace_id !== "string" || !WORKSPACE_ID_PATTERN.test(state.workspace_id)) return null; if (state.conversation_id !== null && state.conversation_id !== undefined && (typeof state.conversation_id !== "string" || state.conversation_id.length === 0 || state.conversation_id.length > 2048)) return null; return { workspace_id: state.workspace_id, conversation_id: typeof state.conversation_id === "string" ? state.conversation_id : null }; };
  const sendHeartbeat = async (state: ContentRelayState, conversationId: string): Promise<void> => { const frame: RelayClientFrame = { type: "tab_heartbeat", workspace_id: state.workspace_id, conversation_id: conversationId }; await api.runtime.sendMessage(frame); };
  const conversationMatches = (state: ContentRelayState, current: string | null): current is string => current !== null && (state.conversation_id === null || state.conversation_id === current);
  const handleAssistantControl = async (text: string): Promise<void> => { try { const state = await loadState(); if (!state) return; const conversationId = await surface.conversationIdentity(); if (!conversationMatches(state, conversationId)) return; await sendHeartbeat(state, conversationId); const frame: RelayClientFrame = { type: "assistant_control", workspace_id: state.workspace_id, text, fingerprint: await fingerprint(text) }; await api.runtime.sendMessage(frame); } catch { /* fail closed */ } };
  const handleDelivery = async (message: DeliverControlMessage): Promise<void> => { try { const state = await loadState(); if (!state || state.workspace_id !== message.workspace_id || !(await surface.isSupported())) return; const conversationId = await surface.conversationIdentity(); if (!conversationMatches(state, conversationId)) return; await sendHeartbeat(state, conversationId); await surface.sendControlText(message.text); const frame: RelayClientFrame = { type: "outbound_sent", workspace_id: state.workspace_id, envelope_id: message.envelope_id }; await api.runtime.sendMessage(frame); } catch { /* durable mailbox remains unacknowledged */ } };
  const stopObserver = surface.observeAssistantControls((text) => { void handleAssistantControl(text); });
  api.runtime.onMessage.addListener((message) => { if (isDeliverControl(message)) void handleDelivery(message); });
  void (async () => { try { const state = await loadState(); const conversationId = await surface.conversationIdentity(); if (state && conversationId) await sendHeartbeat(state, conversationId); } catch { /* best effort */ } })();
  return stopObserver;
}
if (typeof chrome !== "undefined") initializeContentScript(chrome, document, location);
